version: '3.9'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flowforge
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:RELEASE.2024-01-18T22-51-28Z
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address :9001
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio:/data

  n8n:
    image: n8nio/n8n:1.74.1
    environment:
      - N8N_PORT=5678
    ports:
      - "5678:5678"

  backend:
    build:
      context: ..
      dockerfile: infra/node.Dockerfile
      args:
        WORKDIR: apps/backend
    environment:
      - PORT=8080
      - WEB_ORIGIN=http://localhost:5173
      - REDIS_URL=redis://redis:6379
      - N8N_BASE_URL=http://n8n:5678
      - N8N_JOB_WEBHOOK=/webhook/jobs/execute
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_USE_SSL=false
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET=flowforge
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/flowforge
      - JWT_SECRET=dev-secret
    depends_on:
      - redis
      - postgres
      - minio
    command: node dist/index.js
    ports:
      - "8080:8080"

  worker:
    build:
      context: ..
      dockerfile: infra/node.Dockerfile
      args:
        WORKDIR: apps/worker
    environment:
      - REDIS_URL=redis://redis:6379
      - N8N_BASE_URL=http://n8n:5678
      - N8N_JOB_WEBHOOK=/webhook/jobs/execute
    depends_on:
      - redis
      - n8n
    command: node dist/worker.js

  frontend:
    build:
      context: ..
      dockerfile: infra/frontend.Dockerfile
    ports:
      - "5173:80"

  reverse-proxy:
    image: nginx:alpine
    volumes:
      - ./nginx/reverse-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

volumes:
  pgdata:
  minio:
